version: "3.7"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

  app:
    build: goapi/.
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ./goapi:/go/src/work
    ports:
      - 8070:8070
    restart: always

  nuxt:
    build: front_kaou/.
    ports:
      - 3000:3000
    volumes:
      - ./front_kaou:/app
      - /app/node_modules
    tty: true
    working_dir: /app
    command: npm run dev
